config/routes.rb
PccMain::Application.routes.draw do

  resources :notification_logs
  resources :activity_logs
  resources :change_suggestions
  resources :pcc_communication_requests
  resources :pcc_break_requests
  resources :pcc_travel_requests
  resources :travel_tickets

  resources :notifications


  #mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :registrations => 'registrations', :omniauth_callbacks => "omniauth_callbacks" }

  # Misc. static pages
  get '/about'                            => 'home#about'
  get '/registration_confirmation'        => 'home#registration_confirmation'
  get '/backdoor_login'        => 'home#backdoor_login'
  get 'programs/update_timings', :as => 'update_program_timings'
  get 'programs/update_program_donations', :as => 'update_program_donations'
  get 'teacher_schedules/update_timings', :as => 'update_teacher_schedule_timings'
  get 'teacher_schedules/update_centers', :as => 'update_teacher_schedule_centers'
  get 'program_teacher_schedules/update_blockable_teachers', :as => 'update_program_teacher_schedule_blockable_teachers'
  get 'program_teacher_schedules/update_blockable_programs', :as => 'update_program_teacher_schedule_blockable_programs'
  get 'program_teacher_schedules/update_additional_comments', :as => 'update_program_teacher_schedule_additional_comments'
  get 'program_teacher_schedules/update_program_timings', :as => 'update_program_teacher_schedule_program_timings'


  get '/login_as_other_user' => "home#login_as"
  post '/login_as' => "home#become"
  get "/users/autocomplete" => "user#autocomplete_user_email"

  # Resources
  resources :enquiries
  resources :programs do
    member do
      get 'search'
    end
  end
  resources :program_teacher_schedules
  
  #resources :venues do
  #  resources :venue_schedules
  #end

  resources :venues
  resources :kits
  resources :venue_schedules
  resources :kit_schedules do
    member do
      get 'reserve'
    end
  end

  resources :teachers do
    resources :teacher_schedules do
      member do
        get 'reserve'
      end
    end
    member do
      get 'comments'
      get 'search'
    end
  end

  resources :pcc_travel_requests do
      member do
        get 'edit_travel_request'
      end

  end

  resources :pcc_break_requests do
    member do
      get 'edit_break_request'
    end
  end


  # Admin exclusive resources
  #namespace :admin do
  #  resources :users
  #end

  resources :notification_logs do
    collection do
      delete :delete_all
    end
  end




  root :to => 'home#index'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  crm_user_id            :integer
#  firstname              :string(255)
#  lastname               :string(255)
#  address                :string(3000)
#  phone                  :string(255)
#  mobile                 :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  type                   :string(255)
#  deleted_at             :datetime
#  enable                 :boolean          default(FALSE)
#  approver_email         :string(255)
#  message_to_approver    :text
#  approval_email_sent    :boolean          default(FALSE)
#  password_reset_at      :datetime
#  provider               :string(255)
#  sync_ts                :string(255)
#  sync_id                :string(255)
#

module UserExtension
  def by_role(role_name)
    current_role_values = User::ROLE_ACCESS_HIERARCHY.select { |k, v| v[:text] == role_name }.values
    if not current_role_values.empty?
      current_role_access_level = current_role_values.first[:access_level]
      # Take all the roles above the current role's access level, including the current role.
      # So that while getting centers for zonal co-ordinator, will be available even if we check it for kit co-ordinator
      role_names = User::ROLE_ACCESS_HIERARCHY.select { |k, v| v[:access_level] >= current_role_access_level }.values.map { |a| a[:text] }
      puts role_names.inspect
      role_ids=Role.where(:name => role_names).map(&:id)
      find(:all, :conditions => ["access_privileges.role_id in (?)", role_ids])
    else
      find(:all)
    end
  end

  def by_group(group_name)
    current_group_values = User::ROLE_ACCESS_HIERARCHY.select { |k, v| v[:group].include?(group_name) }.values
    if not current_group_values.empty?
      role_names = current_group_values.map { |a| a[:text] }
      puts role_names.inspect
      role_ids=Role.where(:name => role_names).map(&:id)
      find(:all, :conditions => ["access_privileges.role_id in (?)", role_ids])
    else
      []
    end
  end
end


class User < ActiveRecord::Base
  include CommonFunctions

#  require Rails.root.join('lib', 'devise', 'encryptors', 'md5')

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :timeoutable,
         :recoverable, :rememberable, :trackable, :registerable, :omniauthable, :omniauth_providers => [:google_oauth2]

  acts_as_paranoid

  STATE_UNKNOWN             = "Unknown"
  STATE_REQUESTED_APPROVAL  = "Requested Approval"
  STATE_APPROVED            = "Approved"

  EVENT_CREATE              = "Create"
  EVENT_APPROVE             = "Approve"

  has_many :notification_logs, :dependent => :destroy
  has_many :activity_logs, :dependent => :destroy
  attr_accessible :notification_logs, :notification_log_ids, :activity_logs, :activity_log_ids
  has_many :access_privileges, :dependent => :destroy
  has_many :roles, :through => :access_privileges
  has_many :permissions, :through => :roles

  has_many :centers, :through => :access_privileges, :source => :resource, :source_type => 'Center', :extend => UserExtension
  has_many :sectors, :through => :access_privileges, :source => :resource, :source_type => 'Sector', :extend => UserExtension
  has_many :zones, :through => :access_privileges, :source => :resource, :source_type => 'Zone', :extend => UserExtension

  has_many :all_zones,:through => :centers, :source => :zone, :uniq => true

  has_many :sector_centers, :through => :sectors, :source => :centers, :extend => UserExtension
  has_many :zone_centers, :through => :zones, :source => :centers, :extend => UserExtension
  has_many :zone_sectors, :through => :zones, :source => :sectors, :extend => UserExtension

  has_many :zone_center_users, :through => :zone_centers, :source => :users
  has_many :zone_sector_users, :through => :zone_sectors, :source => :users
  has_many :zone_users, :through => :zones, :source => :users
  has_many :all_zone_users, :through => :all_zones, :source => :users


  has_many :teachers, :dependent => :destroy

  #has_many :teacher_schedules
  #has_many :teacher_slots

  ROLE_ACCESS_HIERARCHY =
      {
          :super_admin => {:text => "Super Admin", :access_level => 6, :group => [:geography, :finance, :training]},
          :zonal_coordinator     => {:text => "Zonal Coordinator", :access_level => 5, :group => [:geography]},
          :zao                  => {:text => "ZAO", :access_level => 4, :group => [:geography]},
          :sector_coordinator   => {:text => "Sector Coordinator", :access_level => 3, :group => [:geography]},
          :center_coordinator   => {:text => "Center Coordinator", :access_level => 2, :group => [:geography]},
          :volunteer_committee  => {:text => "Volunteer Committee", :access_level => 0, :group => [:geography]},
          :center_scheduler     => {:text => "Center Scheduler", :access_level => 0, :group => [:geography]},
          :kit_coordinator      => {:text => "Kit Coordinator", :access_level => 0, :group => [:geography]},
          :venue_coordinator    => {:text => "Venue Coordinator", :access_level => 0, :group => [:geography]},
          :treasurer            => {:text => "Treasurer", :access_level => 0, :group => [:geography]},
          :teacher              => {:text => "Teacher", :access_level => 0, :group => [:geography]},
          # NOTE: when creating user-id corresponding to teacher_training_department/ pcc_accounts/ finance_department/ program_announcement, they need to be added to relevant zones.
          :teacher_training_department     => {:text => "Teacher Training Department", :access_level => 0, :group => [:training]},
          :pcc_accounts         => {:text => "PCC Accounts", :access_level => 0, :group => [:finance]},
          :finance_department   => {:text => "Finance Department", :access_level => 0, :group => [:finance]},
          # Dummy group is just a place-holder group, which can be used for all roles which are not related by any hierarchy.
          :program_announcement    => {:text => "Program Announcement", :access_level => 0, :group => [:dummy]},
          :pcc_department         => {:text => "PCC Department", :access_level => 0, :group => [:pcc_requests]},
          :pcc_break_approver         => {:text => "PCC Break Approver", :access_level => 0, :group => [:pcc_requests]},
          :pcc_travel         => {:text => "PCC Travel", :access_level => 0, :group => [:pcc_requests]},
          :pcc_travel_approver      => {:text => "PCC Travel Approver", :access_level => 0, :group => [:pcc_requests]},
          :pcc_travel_vendor         => {:text => "PCC Travel Vendor", :access_level => 0, :group => [:pcc_vendor]},
          :help_desk            => { :text => "Help Desk", :access_level => 0, :group => [:help_desk] },
          :any                  => {:text => "Any", :access_level => -1, :group => []}
    }


  # Setup accessible (or protected) attributes for your model
  attr_accessor :username, :uid
  attr_accessible :email, :password, :password_confirmation, :remember_me, :enable, :approval_email_sent, :receive_email, :receive_sms
  attr_accessible :firstname, :lastname, :address, :phone, :mobile, :access_privilege_names, :type
  attr_accessible :access_privileges, :access_privileges_attributes
  attr_accessible :username, :provider, :uid, :approver_email, :message_to_approver

  accepts_nested_attributes_for :access_privileges, allow_destroy: true

  validates :approver_email, :message_to_approver, :presence => true, :on => :create, :unless => Proc.new { User.current_user.is_super_admin? if User.current_user }
  validates :email, :format => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}
  validates_uniqueness_of :email, :scope => :deleted_at
  validates :phone, :length => {is: 12}, :format => {:with => /0[0-9]{2,4}-[0-9]{6,8}/i}, :allow_blank => true
  validates :mobile, :length => {is: 10}, :numericality => {:only_integer => true}
  validates_uniqueness_of :mobile, :scope => :deleted_at
  validate :validate_approver_email, :on => :create, :unless => Proc.new { User.current_user.is_super_admin? if User.current_user }

  normalize_attributes :approver_email, :email, :firstname, :lastname, :address, :mobile, :phone

  before_save do |user|
    logger.error("Inside User model before save. Values of user.email = #{user.email} and user.enabled? == #{user.enabled?} ")
    if not user.enabled?
      user.type = "PendingUser"
    else
      user.type = nil
    end
    logger.error("Inside User model before save after setting values. Values of user.email = #{user.email} and user.enable == #{user.enable}  and user.type == #{user.type}")
    self.password_reset_at = Time.now if self.encrypted_password_changed?
  end

  after_create do |user|
    user.reload
    UserMailer.approval_email(user).deliver
    user.log_notify(user, STATE_UNKNOWN, STATE_REQUESTED_APPROVAL, EVENT_CREATE, "Approver email: #{user.approver_email}")
    user.update_attribute(:approval_email_sent, true)
  end

  after_save  do |user|
    if user.enable_changed? && user.enable == true
      UserMailer.approved_email(user).deliver
      user.log_notify(user, STATE_REQUESTED_APPROVAL, STATE_APPROVED, EVENT_APPROVE, "")
    end
  end

app/helpers/programs_helper.rb
module ProgramsHelper
  def program_state_tag(prog)
    proc do
      if prog.program_announcement_view?
        if [::Program::STATE_ANNOUNCED, ::Program::STATE_REGISTRATION_CLOSED].include?(prog.state)
          '<span class="label label-success">Announced</span>'
        elsif [::Program::STATE_IN_PROGRESS].include?(prog.state)
          '<span class="label label-info">In-Progress</span>'
        elsif [::Program::STATE_CANCELLED].include?(prog.state)
          '<span class="label label-danger">Cancelled</span>'
        elsif [::Program::STATE_CONDUCTED, ::Program::STATE_TEACHER_CLOSED, ::Program::STATE_ZAO_CLOSED, ::Program::STATE_CLOSED].include?(prog.state)
          '<span class="label label-default">Closed</span>'
        else
          '<span class="label label-default">Unknown</span>'
        end
      else
        if prog.state == ::Program::STATE_PROPOSED
          '<span class="label label-warning">Proposed</span>'
        elsif prog.state == ::Program::STATE_ANNOUNCED
          '<span class="label label-success">Announced</span>'
        elsif prog.state == ::Program::STATE_CANCELLED
          '<span class="label label-danger">Cancelled</span>'
        elsif prog.state == ::Program::STATE_REGISTRATION_CLOSED
          '<span class="label label-warning">Registration Closed</span>'
        elsif prog.state == ::Program::STATE_IN_PROGRESS
          '<span class="label label-info">In-Progress</span>'
        elsif prog.state == ::Program::STATE_CONDUCTED
          '<span class="label label-info">Conducted</span>'
        elsif prog.state == ::Program::STATE_CLOSED
          '<span class="label label-default">Closed</span>'
        elsif prog.state == ::Program::STATE_DROPPED
          '<span class="label label-default">Dropped</span>'
        elsif prog.state == ::Program::STATE_TEACHER_CLOSED
          '<span class="label label-warning">Teacher Closed</span>'
        elsif prog.state == ::Program::STATE_ZAO_CLOSED
          '<span class="label label-info">ZAO Closed</span>'
        elsif prog.state == ::Program::STATE_EXPIRED
          '<span class="label label-danger">Expired</span>'
        else
          '<span class="label label-default">Unknown</span>'
        end
      end
    end.call().html_safe
  end
end

app/views/programs/_search_form.html.erb
<%= form_for(@program, :html => {:class => 'form'}) do |f| %>
  <%= resource_error_messages!(@program) %>

    <div id="centers" class="form-group">
      <%= label_tag 'Center(s)' %>
      <% if @centers.blank? %>
          <%= select_tag 'center_ids', options_for_select(['None Available']), {:multiple => true, :class => 'form-control'} %>
      <% else %>
          <% centers = @centers.sort_by{|e| e.name} %>
          <%= select_tag 'center_ids', options_for_select(centers.map {|c| [c.name, c.id]}), {:multiple => true, :class => 'form-control'} %>
      <% end %>
    </div>
    <div class="form-group">
      <%= label_tag :start_date %>
      <%= text_field_tag 'start_date', nil, :class => 'form-control dateSelect' %>
    </div>
    <div class="form-group">
      <%= label_tag :end_date %>
      <%= text_field_tag 'end_date', nil, :class => 'form-control dateSelect' %>
    </div>

    <%= submit_tag "Search", :disabled => (@centers.blank? ? true: false), :class => 'btn btn-primary btn-lg' %>
<% end %>




<script type='text/javascript'>
$('.dateSelect').datepicker({dateFormat: 'd MM yy (DD)'});
</script>

app/views/programs/_state_bar.html.erb
<div class='row'>
  <div class='page-header'>
<h2>
  <small><%= program_state_tag(@program) %></small> Program Details <small><%= @program.name %> | <%= @program.center.name %></small>
<% if @program.can_update? && !(::Program::FINAL_STATES.include?(@program.state)) %>
    <div class='btn-group'>
  <button type="button" class="btn btn-danger">Update State</button>
  <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">
    <span class="caret"></span>
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <% events = (@program.state_events - ::Program::INTERNAL_NOTIFICATIONS) %>
    <% if events.count > 0 %>
        <% events.each do |ev| %>
            <li> <%= link_to ev, edit_program_path(@program, :trigger => ev) %> </li>
        <% end %>
    <% else %>
        <li class="disabled"><a href="#">No Action Available</a></li>
    <% end %>
  </ul>
</div>
  <% if @program.can_create? %>
    <!-- Single button -->
    <div class="btn-group">
      <button type="button" class="btn btn-primary"> Add New </button>
      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">
        <span class="caret"></span>
        <span class="sr-only">Toggle Dropdown</span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <% unless @program.ready_for_announcement? %>
            <li> <%= link_to 'Add Venue', new_venue_schedule_path(:program_id => @program.id) %> </li>
        <% end %>
        <li><%= link_to 'Add Kit', new_kit_schedule_path(:program_id => @program.id) %></li>
        <li><%= link_to 'Add Teacher', new_program_teacher_schedule_path(:program_id => @program.id) %></li>
      </ul>
    </div>
  <% end %>
<% end %>
</h2>
  </div>
</div>

app/views/programs/new.html.erb
<div class='row'>
  <div class='col-md-12'>
    <div class='page-header'>
      <h2>
        Propose Program
      </h2>
    </div>
    <div class='page-body'>
      <div class='row'>
        <div class='col-md-6'>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/programs/show.html.erb
<div class='row'>
  <div class='col-md-12'>
    <%= render :partial => 'programs/state_bar' %>
  </div>
</div>
<% if @program.can_create? %>
    <% if @program.can_announce? && @program.state == ::Program::STATE_PROPOSED %>
        <div class='alert alert-success'>
          <br>
          <strong>This program is ready for announcement.</strong>
        </div>
    <% elsif !@program.is_announced? && @program.is_active? %>
        <div class='alert alert-danger'>
          This program is not yet ready for announcement.
          <small><%= link_to "[Why?]", '#', :id => 'prog-why-a' %></small>
        </div>
        <div class='row' id='program-announcement-overview' style='display :none;'>
          <div class='col-md-12'>
            <table class='table table-bordered'>
              <tr>
                <td width='25%'><strong>Venue</strong></td>
                <td>
                  <%= (@program.venue_status.map {|vs| vs}).join("<br/>").html_safe %>
                </td>
              </tr>
              <tr>
                <td><strong>Kit</strong></td>
                <td>
                  <%= (@program.kit_status.map {|ks| ks}).join("<br/>").html_safe %>
                </td>
              </tr>
              <tr>
                <td><strong>Teacher</strong></td>
                <td>
                     <%=(@program.teacher_status.map {|ts| ts}).join("<br/>").html_safe %>
                </td>
              </tr>
            </table>
          </div>
        </div>
    <% end %>
<% end %>
<% if @program.can_update? %>
<div class='row'>
  <div class='col-md-12'>
    <h3>Last Update <small><%= @program.last_update %></small></h3>
    <div class = 'row'>
      <div class='col-md-12'>
        <table class='table table-bordered'>
          <tr>
            <td width='20%'><strong> Updated By </strong></td>
            <td>
                <%= @program.last_updated_by_user.fullname rescue ' ' %>
            </td>
          </tr>
          <tr>
            <td><strong> Updated At </strong></td>
            <td><%= @program.last_updated_at.strftime('%d %B %Y (%I:%M%P)') rescue ' ' %></td>
          </tr>
          <tr>
            <td><strong> Comments </strong></td>
            <td><%= @program.comments %></td>
          </tr>
          <% unless @program.feedback.nil? %>
              <tr>
                <td><strong> Feedback </strong></td>
                <td><%= @program.feedback %></td>
              </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>
<% end %>
<div class='row'>
  <h3>Basic Details</h3>
  <div class='col-md-12'>
    <table class='table table-bordered'>
      <tr>
        <td width='20%'><strong>Internal Id</strong></td>
        <td><%= @program.id %></td>
      </tr>
      <tr>
        <td><strong>PID</strong></td>
        <td><%= @program.pid %></td>
      </tr>
      <tr>
        <td><strong>Program Type</strong></td>
        <td><%= @program.program_donation.name %></td>
      </tr>
      <tr>
        <td><strong> Name </strong></td>
        <td><%= @program.name %></td>
      </tr>
      <tr>
        <td width='20%'><strong>Center</strong></td>
        <td><%= @program.locality_name %></td>
      </tr>
      <tr>
        <td><strong>Proposed By</strong></td>
        <td><%= @program.proposer.fullname %></td>
      </tr>
      <tr>
        <td><strong>Start Date</strong></td>
        <td><%= @program.start_date.strftime('%d %B %Y (%A)') %></td>
      </tr>
      <tr>
        <td><strong>End Date</strong></td>
        <td><%= @program.end_date.strftime('%d %B %Y (%A)') %></td>
      </tr>
      <tr>
        <td><strong>Timing (s)</strong></td>
        <td><%= @program.display_timings %></td>
      </tr>
      <% if @program.is_announced? %>
          <tr>
            <td><strong>Capacity</strong></td>
            <td><%= @program.capacity rescue ''%></td>
          </tr>
          <tr>
            <td><strong>Contact Phone (s)</strong></td>
            <td><%= @program.contact_phone rescue ''%></td>
          </tr>
          <tr>
            <td><strong>Contact Email-id (s)</strong></td>
            <td><%= @program.contact_email rescue ''%></td>
          </tr>
      <% end %>
    </table>
  </div>
</div>


  <div class='row'>
    <div class='page-header'>
      <h3>
        Venue Details
      </h3>
    </div>
  </div>

  <div class='row'>
  <div class='col-md-12'>
    <% if !@program.venue_schedules.nil? && @program.venue_schedules.count > 0  %>
        <% @program.venue_schedules.each do |vs| %>
            <%  vs.current_user = current_user %>
            <% if vs.is_connected? %>
                <div class='alert alert-success'>
                  <% if vs.can_update? %>
                    Venue  <%= link_to "#{vs.venue.name}", venue_schedule_path(vs) %> is currently linked to the program.
                  <% elsif vs.can_view? %>
                      Venue  <%= link_to "#{vs.venue.name}", venue_path(vs.venue) %> is currently linked to the program.
                  <% else %>
                      Venue <%= "#{vs.venue.name}" %> is currently linked to the program.
                  <% end %>
                </div>
            <% else %>
                <div class='alert alert-danger'>
                  <% if vs.can_update? %>
                      Venue  <%= link_to "#{vs.venue.name}", venue_schedule_path(vs) %> was earlier linked to the program.
                  <% elsif vs.can_view? %>
                      Venue  <%= link_to "#{vs.venue.name}", venue_path(vs.venue) %> was earlier linked to the program.
                  <% else %>
                      Venue <%= "#{vs.venue.name}" %> was earlier linked to the program.
                  <% end %>
                </div>
            <% end %>
        <% end %>
    <% else %>
    <div class='alert alert-danger'>
      No Venue is associated with this program.
    </div>
    <% end %>
  </div>
</div>

<div class='row'>
  <div class='page-header'>
    <h3>
      Kit Details
    </h3>
  </div>
</div>
<div class='row'>
  <div class='col-md-12'>
    <% if !@program.kit_schedules.nil? && @program.kit_schedules.count > 0 %>
        <% @program.kit_schedules.each do |ks| %>
            <%  ks.current_user = current_user %>
            <% if ks.is_connected? %>
                <div class='alert alert-success'>
                  <% if ks.can_update? %>
                      Kit  <%= link_to "#{ks.kit.name}", kit_schedule_path(ks) %> is currently linked to the program.
                  <% elsif ks.can_view? %>
                      Kit  <%= link_to "#{ks.kit.name}", kit_path(ks.kit) %> is currently linked to the program.
                  <% else %>
                      Kit <%= "#{ks.kit.name}" %> is currently linked to the program.
                  <% end %>
                </div>
            <% else %>
                <div class='alert alert-danger'>
                  <% if ks.can_update? %>
                    Kit  <%= link_to "#{ks.kit.name}", kit_schedule_path(ks) %> was earlier linked to the program.
                  <% elsif ks.can_view? %>
                     Kit  <%= link_to "#{ks.kit.name}", kit_path(ks.kit) %> was earlier linked to the program.
                  <% else %>
                      Kit <%= "#{ks.kit.name}" %> was earlier linked to the program.
                  <% end %>
                </div>
            <% end %>
        <% end %>
    <% else %>
    <div class='alert alert-danger'>
      No Kit is associated with this program.
    </div>
    <% end %>
  </div>
</div>

<div class='row'>
  <div class='page-header'>
    <h3>
      Teacher Details
    </h3>
  </div>
</div>
<div class='row'>
  <div class='col-md-12'>

    <% @program.roles.each {|role| %>
        <h5> <b> <%= role %> (s) </b>
        <small>
          <% if @program.minimum_no_of_teacher(role) == 0 %>
          <b> (optional) </b>
          <% end %>
        </small>
        </h5>
        <% total_teachers = 0 %>
        <% @program.teachers_connected(role).each do |ts| %>
            <% total_teachers += 1 %>
            <%  ts.current_user = current_user %>
            <div class='alert alert-success'>
              <% if ts.can_view_schedule? %>
                  Teacher <%= link_to "#{ts.teacher.user.fullname}", program_teacher_schedule_path(:id => ts.id) %> is currently linked to the program for <b><%= ts.display_timings(role) %></b>.
              <% elsif ts.teacher.can_view? %>
                  Teacher <%= link_to "#{ts.teacher.user.fullname}", teacher_path(ts.teacher) %> is currently linked to the program for <b><%= ts.display_timings(role) %></b>.
              <% else %>
                  Teacher <%= "#{ts.teacher.user.fullname}" %> is currently linked to the program for <b><%= ts.display_timings(role) %></b>.
              <% end %>
            </div>
        <% end %>
        <% @program.teachers_conducted_class(role).each  do |ts| %>
            <% total_teachers += 1 %>
            <%  ts.current_user = current_user %>
            <div class='alert alert-success'>
              <% if ts.can_view_schedule? %>
                  Teacher <%= link_to "#{ts.teacher.user.fullname}", program_teacher_schedule_path(:id => ts.id) %> conducted the program for <b><%= ts.display_timings(role) %></b>.
              <% elsif ts.teacher.can_view? %>
                  Teacher <%= link_to "#{ts.teacher.user.fullname}", teacher_path(ts.teacher) %> conducted the program for <b><%= ts.display_timings(role) %></b>.
              <% else %>
                  Teacher <%= "#{ts.teacher.user.fullname}" %> was earlier linked to the program for <b><%= ts.display_timings(role) %></b>.
              <% end %>
            </div>
        <% end %>
        <% @program.teachers_block_requested(role).each  do |ts| %>
            <%  ts.current_user = current_user %>
            <div class='alert alert-warning'>
              <% if ts.teacher.can_create_program_schedule? or ts.teacher.can_request_program_block? %>
                   <% total_teachers += 1 %>
                  Teacher <%= link_to "#{ts.teacher.user.fullname}", program_teacher_schedule_path(:id => ts.id) %> pending approval for <b><%= ts.display_timings(role) %></b>.
              <% end %>
            </div>
        <% end %>
        <% if total_teachers == 0 %>
            <div class='alert alert-danger'>
              None Attached.
            </div>
        <% end %>
  <% } %>
  </div>
</div>

<script type='text/javascript'>
  $('#prog-why-a').click(function() {
    $('#program-announcement-overview').toggle();
    return false;
  });
</script>