config/routes.rb
PccMain::Application.routes.draw do

  resources :notification_logs
  resources :activity_logs
  resources :change_suggestions
  resources :pcc_communication_requests
  resources :pcc_break_requests
  resources :pcc_travel_requests
  resources :travel_tickets

  resources :notifications


  #mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :registrations => 'registrations', :omniauth_callbacks => "omniauth_callbacks" }

  # Misc. static pages
  get '/about'                            => 'home#about'
  get '/registration_confirmation'        => 'home#registration_confirmation'
  get '/backdoor_login'        => 'home#backdoor_login'
  get 'programs/update_timings', :as => 'update_program_timings'
  get 'programs/update_program_donations', :as => 'update_program_donations'
  get 'teacher_schedules/update_timings', :as => 'update_teacher_schedule_timings'
  get 'teacher_schedules/update_centers', :as => 'update_teacher_schedule_centers'
  get 'program_teacher_schedules/update_blockable_teachers', :as => 'update_program_teacher_schedule_blockable_teachers'
  get 'program_teacher_schedules/update_blockable_programs', :as => 'update_program_teacher_schedule_blockable_programs'
  get 'program_teacher_schedules/update_additional_comments', :as => 'update_program_teacher_schedule_additional_comments'
  get 'program_teacher_schedules/update_program_timings', :as => 'update_program_teacher_schedule_program_timings'


  get '/login_as_other_user' => "home#login_as"
  post '/login_as' => "home#become"
  get "/users/autocomplete" => "user#autocomplete_user_email"

  # Resources
  resources :enquiries
  resources :programs do
    member do
      get 'search'
    end
  end
  resources :program_teacher_schedules
  
  #resources :venues do
  #  resources :venue_schedules
  #end

  resources :venues
  resources :kits
  resources :venue_schedules
  resources :kit_schedules do
    member do
      get 'reserve'
    end
  end

  resources :teachers do
    resources :teacher_schedules do
      member do
        get 'reserve'
      end
    end
    member do
      get 'comments'
      get 'search'
    end
  end

  resources :pcc_travel_requests do
      member do
        get 'edit_travel_request'
      end

  end

  resources :pcc_break_requests do
    member do
      get 'edit_break_request'
    end
  end


  # Admin exclusive resources
  #namespace :admin do
  #  resources :users
  #end

  resources :notification_logs do
    collection do
      delete :delete_all
    end
  end




  root :to => 'home#index'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_filter :authenticate_user!, :except => [:registration_confirmation, :backdoor_login]

  def index

    # @programs = current_user.programs
    # @venues = current_user.venues
    # @kits = current_user.kits
    # @venues = current_user.venues
    # @teachers = current_user.teachers
    # @programs = current_user.programs
    # @teacher = current_user.teachers

    # @pills = ["Programs","Venues","Kits","Teachers"]
    @current_user = current_user
    @new_notifications = current_user.notification_logs.find_all_by_displayed(false)
  end

    def become
      if not ( current_user.is?(:super_admin) or current_user.is?(:zonal_coordinator) or current_user.is?(:zao) )
        redirect_to root_url
      end
      if user =  User.where(:email=>params[:user][:email]).first
        sign_in(:user, user)
        redirect_to root_url # or user_root_url
      else
        flash[:alert] = "You are trying to login as #{params[:user][:email]}, but it is not a valid username / email. Please select proper username /  email."
        redirect_to root_url
      end
    end

  def about
  end

  def registration_confirmation
  end

  def backdoor_login
    @resource = User.new
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_kit_index.html.erb
<div class='row'>
  <div class='col-md-12'>
    <table id = "kit_table" class='display dataTable table table-condensed table-hover table-bordered'>
      <thead>
        <tr>
          <th>Name</th>
          <th>State</th>
          <th>Center</th>
          <th>Max Participants </th>
          <th> Condition </th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @kits.each do |kit| %>
          <tr>
            <td><%= link_to kit.name, kit_path(kit)%> </td>
            <td><%= kit_state_tag(kit) %> </td>
            <td><%= (kit.centers.map {|c| c[:name]}).join(", ") %> </td>
            <td><%= kit.capacity %> </td>
            <td><%= kit.condition %> </td>
            <td><%= link_to "Block", new_kit_schedule_path(:kit_id => kit.id), :class => 'btn btn-primary btn-sm' %>
                <%= link_to "Schedule", kit_schedules_path(:kit_id => kit.id), :class => 'btn btn-primary btn-sm' %>
            </td> 
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/home/_program_index.html.erb
 <div class='row'>
  <div class='col-md-12'>
     <table id="program_table" class='display dataTable table table-condensed table-hover table-bordered'>
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>PID</th>
            <th>Type</th>
            <th>Start</th>
            <th>Slot</th>
            <th>State</th>
          </tr>
        </thead>
        <tbody>
          <% @programs.each do |program| %>
          <tr>
            <td><%= program.id %></td>
            <td><%= link_to program.name, program_path(program)%></td>
            <td><%= program.pid %></td>
            <td><%= (program.program_donation.name rescue '')%></td>
            <td><%= program.start_date.strftime('%d %B %Y') %></td>
            <td><%= program.display_timings %></td>
            <td><%= program_state_tag(program) %></td>
          </tr>
          <% end %>
        </tbody>
    </table>
  </div>
</div>

app/views/home/_teacher_index.html.erb
<div class='row'>
  <div class='col-md-12'>
    <table id = "teacher-table" class='display dataTable table table-condensed table-hover table-bordered'>
      <thead>
        <tr>
          <th>#</th>
          <th>Center</th>
          <th>Name</th>
          <th width='15%'>Active Schedules</th>
          <th width='20%'></th>
        </tr>
      <thead>
      <tbody>
        <% @teachers.each do |teacher| %>
        <tr>
          <td><%= teacher.id %></td>
          <td></td>
          <td><%= link_to teacher.user.fullname, teacher_path(teacher)%> </td>
          <% if false %>
          <td><%=  teacher.teacher_schedules.where('end_date > ?', Time.zone.now).count() %></td>
          <td>
            <%=  link_to "Schedule", teacher_teacher_schedules_path(teacher), :class => 'btn btn-primary btn-sm' %>
          </td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/home/_teachers_index.html.erb
<div class='row'>
  <div class='col-md-12'>
    <table id = "teacher-table" class='display dataTable table table-condensed table-hover table-bordered'>
      <thead>
        <tr>
          <th>#</th>
          <th>Center</th>
          <th>Name</th>
          <th width='15%'>Active Schedules</th>
          <th width='20%'></th>
        </tr>
      <thead>
      <tbody>
        <% @teachers.each do |teacher| %>
        <tr>
          <td><%= teacher.id %></td>
          <td></td>
          <td><%= link_to teacher.fullName, teacher_path(teacher)%> </td>
          <td><%= teacher.teacher_schedules.where('end_date > ?', Time.now).count() %></td>
          <td>
            <%= link_to "Schedule", teacher_teacher_schedules_path(teacher), :class => 'btn btn-primary btn-sm' %> 
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/home/_venue_index.html.erb
<div class='row'>
  <div class='col-md-12'>
    <table id="venue_table" class='display dataTable table table-condensed table-hover table-bordered'>
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Center</th>
          <th>PIN Code</th>
          <th>Capacity</th>
          <th>Contact</th>
          <th ></th>
        </tr>
      </thead>
      <tbody>
        <% @venues.each do |venue| %>
        <tr>
          <td><%= venue.id %></td>
          <td><%= link_to venue.name, venue_path(venue)%></td>           
          <td><%= (venue.centers.map {|c| c[:name]}).join(", ") %></td>
          <td><%= venue.pincode.pincode %></td>
          <td><%= venue.capacity %></td>
          <td><%= venue.contact_name %></td>
          <td>
            <%= link_to "Block", new_venue_schedule_path(:venue_id => venue.id), :class => 'btn btn-primary btn-sm' %>
            <%= link_to "Schedule", venue_schedules_path(:venue_id => venue.id), :class => 'btn btn-primary btn-sm' %>
          </td>
        </tr>
        <% end %>
      </tbody>  
    </table>
  </div>
</div>

app/views/home/about.html.erb
<div class='row'>
  <div class='col-md-12'>
    <div class='page-header'>
      <h2>About PCC</h2>
    </div>
    <div class='page-body'>
      About Page contents go here.
    </div>
  </div>
</div>

app/views/home/backdoor_login.html.erb
<div class='col-md-12'>
  <div class='page-header'>
    <h2>Genie Admin Sign-in</h2>
  </div>

 <div class='page-body'>
    <div class='row'>
      <div class='col-md-6 col-md-offset-1'>
        <%= form_for(@resource, :url => session_path(@resource), :html => { :class => 'form' }) do |f| %>
            <div class='form-group'>
              <%= f.label :email %>
              <%= f.email_field :email, :class => 'form-control', :autofocus => true %>
            </div>
            <div class='form-group'>
              <%= f.label :password %>
              <%= f.password_field :password, :class => 'form-control' %>
            </div>
            <%= f.submit "Sign-in", :class => 'btn btn-lg btn-primary' %>
            <%= link_to "Sign in with Google", omniauth_authorize_path(@resource, :google_oauth2), :class => 'btn btn-lg btn-primary' %> <br/>
        <% end %>
      </div>
    </div>
  </div>

</div>
</div>

app/views/home/index.html.erb
<% centers = current_user.accessible_center_ids %>
<div class='row'>
  <div class='col-md-12'>
    <br><br>
    <% unless current_user.access_privileges.empty? %>
        <div class="panel panel-info">
          <div class="panel-heading"><h2>Namaskaram <%= @current_user.firstname %>! </h2></div>
          <div class="panel-body">
            <p>
              <% last_sign_in_at = @current_user.last_sign_in_at %>
              <% unless last_sign_in_at.nil? %>
                <b> You last logged in at </b> <i><%= last_sign_in_at.strftime("%I:%M %P") %></i> <b>on</b> <i><%= last_sign_in_at.strftime("%d %B %Y") %></i>
              <% end %>
            </p>
          </div>
          <!-- List group -->
          <ul class="list-group">
            <% no_of = @new_notifications.empty? ? 0 :  @new_notifications.count %>
            <li class="list-group-item"><b> You have </b> <%= no_of %> <b>new</b> <%= link_to "Notifications", notification_logs_path %> </li>
            <li class="list-group-item"><b> View your past </b><%= link_to "Activity", activity_logs_path %></li>
          </ul>
        </div>
    <% else %>
        <div class="alert alert-danger">[ ACCESS DENIED ] Please contact your coordinator for access. </div>
    <% end %>
  </div>
</div>
<% if false %>
<style type="text/css" title="currentStyle">
      @import "../ext/css/jquery.dataTables.css";
</style>
<script src="../ext/js/jquery.dataTables.js"type="text/javascript">
</script>
<script type="text/javascript">
  $(document).ready(function() {
    $('#kit_table').dataTable();
    $('#venue_table').dataTable();
    $('#program_table').dataTable();
    $('#teacher_table').dataTable();
  });
</script>
<div class='row'>
  <div class='col-md-12'>
    <div class="tabbable">
    <ul id = "myTab" class="nav nav-pills">
        <li class="active"><a href="#Programs" data-toggle="pill">Programs</a></li>
        <li ><a href="#Venues" data-toggle="pill">Venues</a></li>
        <li ><a href="#Kits" data-toggle="pill">Kits</a></li>
        <li ><a href="#Teachers" data-toggle="pill">Teachers</a></li>
    </ul>
    <div class="row" style="padding: 0.7em"></div>
      <% if false %>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane active" id="Programs">
        <%= render :partial => 'home/program_index' %>
      </div>
      <div class="tab-pane " id="Venues">
        <%= render :partial => 'home/venue_index' %>
      </div>
      <div class="tab-pane " id="Kits">
        <%= render :partial => 'home/kit_index' %>
      </div>
      <div class="tab-pane " id="Teachers">
        <%= render :partial => 'home/teacher_index' %>
      </div>

      </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/home/login_as.erb
<div class='row'>
  <div class='col-md-12'>
    <div class='page-header'>
      <h3> Please enter email of the User you want to login as </h3>
    </div>
    <div class='page-body'>
        <%= form_for User.new, {:url => "/login_as", :method => "post", :html => {:id => "form_login_as",:class => "navbar-collapse"}}  do |f|
          f.autocomplete_field :email, "/users/autocomplete", :value => ""
        end %>
    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">

    $('#user_email').bind('railsAutocomplete.select' , function(event, data){
        $('#form_login_as').submit();
    });

</script>

app/views/home/registration_confirmation.html.erb
<div class='row'>
  <div class='col-md-12'>
    <div class='page-body'>
      <div class="bs-callout bs-callout-info">
      <h4>Account Activation Required</h4>
      <p>
        An e-mail has been sent to your approver with your message to approve. Please contact approver for approval.
      </p>
      <br/>

    </div>
    </div>
  </div>
</div>