config/routes.rb
PccMain::Application.routes.draw do

  resources :notification_logs
  resources :activity_logs
  resources :change_suggestions
  resources :pcc_communication_requests
  resources :pcc_break_requests
  resources :pcc_travel_requests
  resources :travel_tickets

  resources :notifications


  #mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :registrations => 'registrations', :omniauth_callbacks => "omniauth_callbacks" }

  # Misc. static pages
  get '/about'                            => 'home#about'
  get '/registration_confirmation'        => 'home#registration_confirmation'
  get '/backdoor_login'        => 'home#backdoor_login'
  get 'programs/update_timings', :as => 'update_program_timings'
  get 'programs/update_program_donations', :as => 'update_program_donations'
  get 'teacher_schedules/update_timings', :as => 'update_teacher_schedule_timings'
  get 'teacher_schedules/update_centers', :as => 'update_teacher_schedule_centers'
  get 'program_teacher_schedules/update_blockable_teachers', :as => 'update_program_teacher_schedule_blockable_teachers'
  get 'program_teacher_schedules/update_blockable_programs', :as => 'update_program_teacher_schedule_blockable_programs'
  get 'program_teacher_schedules/update_additional_comments', :as => 'update_program_teacher_schedule_additional_comments'
  get 'program_teacher_schedules/update_program_timings', :as => 'update_program_teacher_schedule_program_timings'


  get '/login_as_other_user' => "home#login_as"
  post '/login_as' => "home#become"
  get "/users/autocomplete" => "user#autocomplete_user_email"

  # Resources
  resources :enquiries
  resources :programs do
    member do
      get 'search'
    end
  end
  resources :program_teacher_schedules
  
  #resources :venues do
  #  resources :venue_schedules
  #end

  resources :venues
  resources :kits
  resources :venue_schedules
  resources :kit_schedules do
    member do
      get 'reserve'
    end
  end

  resources :teachers do
    resources :teacher_schedules do
      member do
        get 'reserve'
      end
    end
    member do
      get 'comments'
      get 'search'
    end
  end

  resources :pcc_travel_requests do
      member do
        get 'edit_travel_request'
      end

  end

  resources :pcc_break_requests do
    member do
      get 'edit_break_request'
    end
  end


  # Admin exclusive resources
  #namespace :admin do
  #  resources :users
  #end

  resources :notification_logs do
    collection do
      delete :delete_all
    end
  end




  root :to => 'home#index'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  crm_user_id            :integer
#  firstname              :string(255)
#  lastname               :string(255)
#  address                :string(3000)
#  phone                  :string(255)
#  mobile                 :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  type                   :string(255)
#  deleted_at             :datetime
#  enable                 :boolean          default(FALSE)
#  approver_email         :string(255)
#  message_to_approver    :text
#  approval_email_sent    :boolean          default(FALSE)
#  password_reset_at      :datetime
#  provider               :string(255)
#  sync_ts                :string(255)
#  sync_id                :string(255)
#

module UserExtension
  def by_role(role_name)
    current_role_values = User::ROLE_ACCESS_HIERARCHY.select { |k, v| v[:text] == role_name }.values
    if not current_role_values.empty?
      current_role_access_level = current_role_values.first[:access_level]
      # Take all the roles above the current role's access level, including the current role.
      # So that while getting centers for zonal co-ordinator, will be available even if we check it for kit co-ordinator
      role_names = User::ROLE_ACCESS_HIERARCHY.select { |k, v| v[:access_level] >= current_role_access_level }.values.map { |a| a[:text] }
      puts role_names.inspect
      role_ids=Role.where(:name => role_names).map(&:id)
      find(:all, :conditions => ["access_privileges.role_id in (?)", role_ids])
    else
      find(:all)
    end
  end

  def by_group(group_name)
    current_group_values = User::ROLE_ACCESS_HIERARCHY.select { |k, v| v[:group].include?(group_name) }.values
    if not current_group_values.empty?
      role_names = current_group_values.map { |a| a[:text] }
      puts role_names.inspect
      role_ids=Role.where(:name => role_names).map(&:id)
      find(:all, :conditions => ["access_privileges.role_id in (?)", role_ids])
    else
      []
    end
  end
end


class User < ActiveRecord::Base
  include CommonFunctions

#  require Rails.root.join('lib', 'devise', 'encryptors', 'md5')

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :timeoutable,
         :recoverable, :rememberable, :trackable, :registerable, :omniauthable, :omniauth_providers => [:google_oauth2]

  acts_as_paranoid

  STATE_UNKNOWN             = "Unknown"
  STATE_REQUESTED_APPROVAL  = "Requested Approval"
  STATE_APPROVED            = "Approved"

  EVENT_CREATE              = "Create"
  EVENT_APPROVE             = "Approve"

  has_many :notification_logs, :dependent => :destroy
  has_many :activity_logs, :dependent => :destroy
  attr_accessible :notification_logs, :notification_log_ids, :activity_logs, :activity_log_ids
  has_many :access_privileges, :dependent => :destroy
  has_many :roles, :through => :access_privileges
  has_many :permissions, :through => :roles

  has_many :centers, :through => :access_privileges, :source => :resource, :source_type => 'Center', :extend => UserExtension
  has_many :sectors, :through => :access_privileges, :source => :resource, :source_type => 'Sector', :extend => UserExtension
  has_many :zones, :through => :access_privileges, :source => :resource, :source_type => 'Zone', :extend => UserExtension

  has_many :all_zones,:through => :centers, :source => :zone, :uniq => true

  has_many :sector_centers, :through => :sectors, :source => :centers, :extend => UserExtension
  has_many :zone_centers, :through => :zones, :source => :centers, :extend => UserExtension
  has_many :zone_sectors, :through => :zones, :source => :sectors, :extend => UserExtension

  has_many :zone_center_users, :through => :zone_centers, :source => :users
  has_many :zone_sector_users, :through => :zone_sectors, :source => :users
  has_many :zone_users, :through => :zones, :source => :users
  has_many :all_zone_users, :through => :all_zones, :source => :users


  has_many :teachers, :dependent => :destroy

  #has_many :teacher_schedules
  #has_many :teacher_slots

  ROLE_ACCESS_HIERARCHY =
      {
          :super_admin => {:text => "Super Admin", :access_level => 6, :group => [:geography, :finance, :training]},
          :zonal_coordinator     => {:text => "Zonal Coordinator", :access_level => 5, :group => [:geography]},
          :zao                  => {:text => "ZAO", :access_level => 4, :group => [:geography]},
          :sector_coordinator   => {:text => "Sector Coordinator", :access_level => 3, :group => [:geography]},
          :center_coordinator   => {:text => "Center Coordinator", :access_level => 2, :group => [:geography]},
          :volunteer_committee  => {:text => "Volunteer Committee", :access_level => 0, :group => [:geography]},
          :center_scheduler     => {:text => "Center Scheduler", :access_level => 0, :group => [:geography]},
          :kit_coordinator      => {:text => "Kit Coordinator", :access_level => 0, :group => [:geography]},
          :venue_coordinator    => {:text => "Venue Coordinator", :access_level => 0, :group => [:geography]},
          :treasurer            => {:text => "Treasurer", :access_level => 0, :group => [:geography]},
          :teacher              => {:text => "Teacher", :access_level => 0, :group => [:geography]},
          # NOTE: when creating user-id corresponding to teacher_training_department/ pcc_accounts/ finance_department/ program_announcement, they need to be added to relevant zones.
          :teacher_training_department     => {:text => "Teacher Training Department", :access_level => 0, :group => [:training]},
          :pcc_accounts         => {:text => "PCC Accounts", :access_level => 0, :group => [:finance]},
          :finance_department   => {:text => "Finance Department", :access_level => 0, :group => [:finance]},
          # Dummy group is just a place-holder group, which can be used for all roles which are not related by any hierarchy.
          :program_announcement    => {:text => "Program Announcement", :access_level => 0, :group => [:dummy]},
          :pcc_department         => {:text => "PCC Department", :access_level => 0, :group => [:pcc_requests]},
          :pcc_break_approver         => {:text => "PCC Break Approver", :access_level => 0, :group => [:pcc_requests]},
          :pcc_travel         => {:text => "PCC Travel", :access_level => 0, :group => [:pcc_requests]},
          :pcc_travel_approver      => {:text => "PCC Travel Approver", :access_level => 0, :group => [:pcc_requests]},
          :pcc_travel_vendor         => {:text => "PCC Travel Vendor", :access_level => 0, :group => [:pcc_vendor]},
          :help_desk            => { :text => "Help Desk", :access_level => 0, :group => [:help_desk] },
          :any                  => {:text => "Any", :access_level => -1, :group => []}
    }


  # Setup accessible (or protected) attributes for your model
  attr_accessor :username, :uid
  attr_accessible :email, :password, :password_confirmation, :remember_me, :enable, :approval_email_sent, :receive_email, :receive_sms
  attr_accessible :firstname, :lastname, :address, :phone, :mobile, :access_privilege_names, :type
  attr_accessible :access_privileges, :access_privileges_attributes
  attr_accessible :username, :provider, :uid, :approver_email, :message_to_approver

  accepts_nested_attributes_for :access_privileges, allow_destroy: true

  validates :approver_email, :message_to_approver, :presence => true, :on => :create, :unless => Proc.new { User.current_user.is_super_admin? if User.current_user }
  validates :email, :format => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}
  validates_uniqueness_of :email, :scope => :deleted_at
  validates :phone, :length => {is: 12}, :format => {:with => /0[0-9]{2,4}-[0-9]{6,8}/i}, :allow_blank => true
  validates :mobile, :length => {is: 10}, :numericality => {:only_integer => true}
  validates_uniqueness_of :mobile, :scope => :deleted_at
  validate :validate_approver_email, :on => :create, :unless => Proc.new { User.current_user.is_super_admin? if User.current_user }

  normalize_attributes :approver_email, :email, :firstname, :lastname, :address, :mobile, :phone

  before_save do |user|
    logger.error("Inside User model before save. Values of user.email = #{user.email} and user.enabled? == #{user.enabled?} ")
    if not user.enabled?
      user.type = "PendingUser"
    else
      user.type = nil
    end
    logger.error("Inside User model before save after setting values. Values of user.email = #{user.email} and user.enable == #{user.enable}  and user.type == #{user.type}")
    self.password_reset_at = Time.now if self.encrypted_password_changed?
  end

  after_create do |user|
    user.reload
    UserMailer.approval_email(user).deliver
    user.log_notify(user, STATE_UNKNOWN, STATE_REQUESTED_APPROVAL, EVENT_CREATE, "Approver email: #{user.approver_email}")
    user.update_attribute(:approval_email_sent, true)
  end

  after_save  do |user|
    if user.enable_changed? && user.enable == true
      UserMailer.approved_email(user).deliver
      user.log_notify(user, STATE_REQUESTED_APPROVAL, STATE_APPROVED, EVENT_APPROVE, "")
    end
  end

app/helpers/teachers_helper.rb
module TeachersHelper

  def teacher_state_tag(t)
    proc do
      case t.state
        when ::Teacher::STATE_ATTACHED
          '<span class="label label-success">Attached</span>'
        when ::Teacher::STATE_UNATTACHED
          '<span class="label label-default">Not Attached</span>'
        else
          '<span class="label label-default">Unknown</span>'
      end
    end.call().html_safe
  end
end

app/views/teachers/_additional_comment_form.html.erb
<%= form_for(@teacher, :html => { :class => 'form' }) do |f| %>
    <%= resource_error_messages!(@teacher) %>

    <div class='form-group'>
      <label>Comments </label><small> (optional) </small>
      <textarea name='additional_comments' class='form-control'><%= @teacher.additional_comments %> </textarea>
    </div>

    <%= submit_tag 'Update', :class => 'btn btn-lg btn-primary' %>
    <%= link_to "Cancel", :back, :class => 'btn btn-primary btn-lg :hover' %>
<% end %>

app/views/teachers/_search_form.html.erb
<%= form_for(@teacher, :html => {:class => 'form'}) do |f| %>
  <%= resource_error_messages!(@teacher) %>

    <div id="teachers" class="form-group">
      <%= label_tag 'Teachers(s)' %>
      <% if @teachers.blank? %>
          <%= select_tag 'teacher_ids', options_for_select(['None Available']), {:multiple => true, :class => 'form-control'} %>
      <% else %>
          <% teachers = @teachers.sort_by{|e| e.user.fullname} %>
          <%= select_tag 'teacher_ids', options_for_select(teachers.map {|e| [e.user.fullname, e.id]}), {:multiple => true, :class => 'form-control'} %>
      <% end %>
    </div>
    <div class="form-group">
      <%= label_tag :start_date %>
      <%= text_field_tag 'start_date', nil, :class => 'form-control dateSelect' %>
    </div>
    <div class="form-group">
      <%= label_tag :end_date %>
      <%= text_field_tag 'end_date', nil, :class => 'form-control dateSelect' %>
    </div>

    <%= submit_tag "Search", :disabled => (@teachers.blank? ? true: false), :class => 'btn btn-primary btn-lg' %>
<% end %>




<script type='text/javascript'>
$('.dateSelect').datepicker({dateFormat: 'd MM yy (DD)'});
</script>

app/views/teachers/_state_bar.html.erb
<h2>
  <small><%= teacher_state_tag(@teacher) %></small> Teacher <small><%= @teacher.user.fullname %></small>
  <% if false %>
    <% if !::Teacher::FINAL_STATES.include?(@teacher.state) && @teacher.can_update? %>
        <div class='btn-group'>
          <button type="button" class="btn btn-danger">Update State</button>
          <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <% events = @teacher.state_events %>
            <% if events.count > 0 %>
                <% events.each do |ev| %>
                    <li> <%= link_to ev, edit_teacher_path(:id => @teacher.id, :trigger => ev) %> </li>
                <% end %>
            <% else %>
                <li class="disabled"><a href="#">No Action Available</a></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <% end %>
    <span class='pull-right'>
        <%= link_to "Back to Teachers", teachers_path, :class => 'btn btn-primary' %>
    </span>
</h2>

app/views/teachers/_state_update_comment.html.erb
<div class='form-group'>
  <% if ::Teacher::EVENTS_WITH_COMMENTS.include?(@trigger) %>
      <% unless @teacher.comment_category.empty? %>
          <label for='comment_category'>Comments</label> <small>(required)</small>
          <%= select_tag 'comment_category', options_for_select(@teacher.comment_category), :class => 'form-control' %>
          <br>
          <label>Details</label>
          <textarea name='comments' class='form-control'></textarea>
      <% else %>
          <label>Comments</label> <small>(required)</small>
          <textarea name='comments' class='form-control'></textarea>
      <% end %>
  <% elsif ::Teacher::EVENTS_WITH_FEEDBACK.include?(@trigger) %>
      <label>Feedback</label> <small>(required)</small>
      <textarea name='feedback' class='form-control'></textarea>
  <% else %>
      <label>Comments</label> <small>(optional)</small>
      <textarea name='comments' class='form-control'></textarea>
  <% end %>
</div>

app/views/teachers/_state_update_confirmation_msg.html.erb
<% if ::Teacher::EVENTS_WITH_COMMENTS.include?(@trigger) %>
    <div class='alert alert-warning'>
<% else %>
    <div class='alert alert-info'>
<% end %>
<h3>Confirmation: </h3>
<p>
  <% if @trigger == ::Teacher::EVENT_UNATTACH %>
      <strong>WARNING: </strong> This will remove the teacher from all center(s) and delete all his/her schedules. This action cannot be reverted. Are you sure you want to proceed?
  <% end %>
</p>
</div>

app/views/teachers/additional_comment.html.erb
<div class='row'>
  <div class='col-md-12'>
    <div class='page-header'>
      <h2> Note for Teacher Scheduler </h2>
    </div>
    <div class='page-body'>
      <div class='row'>
        <div class='col-md-6'>
          <%= render 'additional_comment_form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/teachers/edit.html.erb
<div class='row'>
  <div class='col-md-12'>
    <h2>
      Teacher <small><%= @teacher.user.fullname %></small>
    </h2>
  </div>
</div>
<%= form_for(@teacher, :html => {:class => 'form'}) do |f| %>
<%= resource_error_messages!(@teacher) %>
<%= hidden_field_tag 'trigger', @trigger %>

<% unless @teacher.errors.any? %>
<div class='row'>
  <div class='col-md-12'>
    <%= render :partial => 'teachers/state_update_confirmation_msg' %>
  </div>
</div>
<% end %>
<div class='row'>
  <div class='col-md-12'>
    <%= render :partial => 'teachers/state_additional_data' %>
  </div>
</div>
<div class='row'>
  <div class='col-md-12'>
    <%= render :partial => 'teachers/state_update_comment' %>
  </div>
</div>
<div class='row'>
  <div class='col-md-12'>
    <%= submit_tag "Update", :class => 'btn btn-primary btn-lg' %>
    <%= link_to "Cancel", :back, :class => 'btn btn-primary btn-lg :hover' %>
  </div>
</div>
<% end %>

app/views/teachers/index.html.erb
<script type="text/javascript">
    $(document).ready(function() {
        $('#teacher_table').dataTable({
            "sPaginationType": "bootstrap",
            "sDom": 'T<"clear">lfrtip',
            "oTableTools": {
                "aButtons": [
                    "print",
                    {
                        "sExtends":    "collection",
                        "sButtonText": "Save",
                        "aButtons":    [ "csv", "xls", "pdf" ]
                    }
                ]
            }
        } );
    });
</script>

<div class='row'>
  <div class='col-md-12'>
    <h2>Available Teachers
          <span class='pull-right'>
            <%= link_to "Advance Search", search_teacher_path(:id => 0), :class => 'btn btn-primary btn-sm' unless @searchable_teachers.blank? %>
          </span>
      <hr>
    </h2>
  </div>
</div>

<% if @teachers.blank? %>
    <div class="alert alert-danger"> No Teachers Found.</div>
<% else %>
<table id="teacher_table" class='display dataTable table table-condensed table-hover table-bordered'>
  <thead>
  <tr>
    <th>ID #</th>
    <th>Name</th>
    <th>Part-Time</th>
    <th>Program Types</th>
    <th>Zone(s)</th>
    <th>Center(s)</th>
    <%-# <th>Current State</th> %>
    <th width='15%'></th>
  </tr>
  </thead>
  <tbody>
  <% @teachers.each do |teacher| %>
      <% teacher.current_user = current_user %>
      <tr>
        <td><%= teacher.id %></td>
        <td><%= teacher.user.fullname %></td>
        <td><%= teacher.full_time? ? "No" : "Yes" %></td>
        <td>
          <% teacher.role_program_types.each { |role, pts | %>
            <%= ["[#{role}] #{(pts.map{|pt| pt[:name]}).sort.join(", ")}"].join("; ") unless pts.blank? %>
          <% } %>
        </td>
        <td><%= teacher.display_zones rescue '' %></td>
        <% if teacher.full_time? %>
            <td><%= '[All Centers in Zone]' %></td>
        <% else %>
            <td><%= (teacher.centers.map {|c| c[:name]}).join(", ") %></td>
        <% end %>
        <% if false %>
            <td><%= teacher_state_tag(teacher) %></td>
        <% end %>
        <td>
          <%= link_to "Show", teacher_path(teacher), :class => 'btn btn-primary btn-sm' if teacher.can_view? || teacher.is_current_user? %>
          <% if teacher.state == Teacher::STATE_ATTACHED %>
              <%= link_to "Schedule", teacher_teacher_schedules_path(teacher), :class => 'btn btn-primary btn-sm' if teacher.can_view_schedule?  %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<% end %>

app/views/teachers/search.html.erb
<div class='row'>
  <div class='col-md-12'>
    <div class='page-header'>
      <h2>
        Search Teacher Schedules
      </h2>
    </div>
    <div class='page-body'>
      <div class='row'>
        <div class='col-md-6'>
          <%= render 'search_form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/teachers/search_results.html.erb
<div class='row'>
  <div class='col-md-12'>
    <h2>Teacher Schedules
    </h2>
  </div>
</div>
<br>
<script type="text/javascript" src="https://www.google.com/jsapi?autoload={'modules':[{'name':'visualization',
       'version':'1','packages':['timeline']}]}"></script>
<script type="text/javascript">

    google.setOnLoadCallback(drawChart);
    function drawChart() {
        var container = document.getElementById('teacher_schedule_search_results');
        var chart = new google.visualization.Timeline(container);
        var dataTable = new google.visualization.DataTable();
        dataTable.addColumn({ type: 'string', id: 'Position' });
        dataTable.addColumn({ type: 'string', id: 'Name' });
        dataTable.addColumn({ type: 'string', role: 'style' });
        dataTable.addColumn({ type: 'date', id: 'Start' });
        dataTable.addColumn({ type: 'date', id: 'End' });
        var teacher_schedules = <%= raw @teacher_schedules.to_json %>;
        for (index = 0; index < teacher_schedules.length; ++index) {
            var value = teacher_schedules[index];
            var color;
            switch(value[4]) {
                case "yellow":
                    color = '#FFFF00';
                    break;
                case "green":
                    color = '#00CC00';
                    break;
                case "red":
                    color = '#E60000';
                    break;
                case "blue":
                    color = '#0066FF';
                    break;
                case "white":
                    color = '#EEEEEE';
                    break;
            }
            dataTable.addRow([value[0], value[1], color,
                new Date(value[2][0], value[2][1], value[2][2], value[2][3], value[2][4], value[2][5]),
                new Date(value[3][0], value[3][1], value[3][2], value[3][3], value[3][4], value[3][5])
            ]);
        };
        var options = {};

        function selectHandler() {
            var selectedItem = chart.getSelection()[0];
            if (selectedItem) {

                var t_description = dataTable.getValue(selectedItem.row, 0);
                var t_elements = t_description.split("(#");
                if (t_elements.length < 2){
                    return;
                }
                tid_str = (t_elements[1]).slice(0,-1);
                var tid = parseInt(tid_str);
                if (isNaN(tid)) {
                    return;
                }

                var description = dataTable.getValue(selectedItem.row, 1);
                var elements = description.split("(*");
                var pid = 0;
                if (elements.length < 2){
                    elements = description.split("(#");
                    if (elements.length < 2){
                        return;
                    }
                    pid = 1;
                }
                tsid_str = (elements[1]).slice(0,-1);
                var tsid = parseInt(tsid_str);
                if (isNaN(tsid)) {
                    return;
                }
                var path = "";
                if (pid == 0){
                    path = Routes.teacher_teacher_schedule_path(tid, tsid);
                }else{
                    path = Routes.program_teacher_schedule_path(tsid);
                }

                // extract id for the resource
                var win = window.open(path, '_blank');
                if(win){
                    //Browser has allowed it to be opened
                    win.focus();
                }else{
                    //Browser has blocked it
                    alert('Please allow popups for this site');
                }
            }
        }

        google.visualization.events.addListener(chart, 'select', selectHandler);
        chart.draw(dataTable, options);
    }
</script>
<div id="teacher_schedule_search_results" style="width: 900px; height: 400px;"></div>

app/views/teachers/show.html.erb
<% if @teacher.can_view? %>
<div class='row'>
  <div class='col-md-12'>
    <%= render :partial => 'state_bar' %>
  </div>
</div>
<% if @teacher.can_update? %>
    <div class='row'>
      <div class='col-md-12'>
        <h3>Last Update <small><%= @teacher.last_update %></small></h3>
        <div class = 'row'>
          <div class='col-md-12'>
            <table class='table table-bordered'>
              <tr>
                <td width='20%'><strong> Updated By </strong></td>
                <td>
                    <%= @teacher.last_updated_by_user.fullname rescue ' ' %>
                </td>
              </tr>
              <tr>
                <td><strong> Updated At </strong></td>
                <td><%= @teacher.last_updated_at.strftime('%d %B %Y (%I:%M%P)') rescue ' ' %></td>
              </tr>
              <tr>
                <td><strong> Comments </strong></td>
                <td><%= @teacher.comments %></td>
              </tr>
              <tr>
            </table>
          </div>
        </div>
      </div>
    </div>
<% end %>
<div class='row'>
  <h3>Details</h3>
  <div class='col-md-12'>
    <table class='table table-bordered'>
      <tr>
        <td width='20%'><strong>ID #</strong></td>
        <td><%= @teacher.id %></td>
      </tr>
      <tr>
        <td><strong>T No</strong></td>
        <td><%= @teacher.t_no %></td>
      </tr>
      <tr>
        <td><strong>Part-Time</strong></td>
        <td><%= @teacher.full_time? ? "No" : "Yes" %></td>
      </tr>
      <% @teacher.role_program_types.each {|role, program_types| %>
      <tr>
        <td><strong><%= role %></strong></td>
        <td><%= (program_types.map {|pt| pt[:name]}).sort.join(", ") %></td>
      </tr>
      <% } %>
      <tr>
        <td><strong>Zone(s)</strong></td>
        <td><%= @teacher.display_zones rescue '' %></td>
      </tr>
      <tr>
        <td><strong>Center(s)</strong></td>
        <% if @teacher.full_time? %>
            <td><%= '[All Centers in Zone]' %></td>
        <% else %>
            <td><%= (@teacher.centers.map {|c| c[:name]}).join(", ") %></td>
        <% end %>
      </tr>
    </table>
  </div>
</div>
<div class='row'>
  <h3>Contact</h3>
  <div class='col-md-12'>
    <table class='table table-bordered'>
      <tr>
        <td width='20%'><strong>Mobile</strong></td>
        <td><%= @teacher.user.mobile %></td>
      </tr>
      <tr>
        <td width='20%'><strong>Email</strong></td>
        <td><%= @teacher.user.email %></td>
      </tr>
      <tr>
        <td width='20%'><strong>Phone</strong></td>
        <td><%=  @teacher.user.phone %></td>
      </tr>
      <tr>
        <td width='20%'><strong>Address</strong></td>
        <td><%=  @teacher.user.address %></td>
      </tr>
    </table>
  </div>
</div>
<% end %>