config/routes.rb
PccMain::Application.routes.draw do

  resources :notification_logs
  resources :activity_logs
  resources :change_suggestions
  resources :pcc_communication_requests
  resources :pcc_break_requests
  resources :pcc_travel_requests
  resources :travel_tickets

  resources :notifications


  #mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :registrations => 'registrations', :omniauth_callbacks => "omniauth_callbacks" }

  # Misc. static pages
  get '/about'                            => 'home#about'
  get '/registration_confirmation'        => 'home#registration_confirmation'
  get '/backdoor_login'        => 'home#backdoor_login'
  get 'programs/update_timings', :as => 'update_program_timings'
  get 'programs/update_program_donations', :as => 'update_program_donations'
  get 'teacher_schedules/update_timings', :as => 'update_teacher_schedule_timings'
  get 'teacher_schedules/update_centers', :as => 'update_teacher_schedule_centers'
  get 'program_teacher_schedules/update_blockable_teachers', :as => 'update_program_teacher_schedule_blockable_teachers'
  get 'program_teacher_schedules/update_blockable_programs', :as => 'update_program_teacher_schedule_blockable_programs'
  get 'program_teacher_schedules/update_additional_comments', :as => 'update_program_teacher_schedule_additional_comments'
  get 'program_teacher_schedules/update_program_timings', :as => 'update_program_teacher_schedule_program_timings'


  get '/login_as_other_user' => "home#login_as"
  post '/login_as' => "home#become"
  get "/users/autocomplete" => "user#autocomplete_user_email"

  # Resources
  resources :enquiries
  resources :programs do
    member do
      get 'search'
    end
  end
  resources :program_teacher_schedules
  
  #resources :venues do
  #  resources :venue_schedules
  #end

  resources :venues
  resources :kits
  resources :venue_schedules
  resources :kit_schedules do
    member do
      get 'reserve'
    end
  end

  resources :teachers do
    resources :teacher_schedules do
      member do
        get 'reserve'
      end
    end
    member do
      get 'comments'
      get 'search'
    end
  end

  resources :pcc_travel_requests do
      member do
        get 'edit_travel_request'
      end

  end

  resources :pcc_break_requests do
    member do
      get 'edit_break_request'
    end
  end


  # Admin exclusive resources
  #namespace :admin do
  #  resources :users
  #end

  resources :notification_logs do
    collection do
      delete :delete_all
    end
  end




  root :to => 'home#index'

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  include CommonFunctions

  has_many :activity_logs, :as => :model, :inverse_of => :model, :dependent => :destroy
  has_many :notification_logs, :as => :model, :inverse_of => :model, :dependent => :destroy

  acts_as_paranoid

  attr_accessor :current_user
  attr_accessible :current_user

  # There two are hacks, since rails_admin is updating the state of the teacher, instead of the regular controller route
  attr_accessor :last_state
  attr_accessible :last_state

  belongs_to :last_updated_by_user, :class_name => User
  attr_accessible :last_update, :last_updated_at

  has_and_belongs_to_many :centers, :after_add => :add_access_privilege, :after_remove  => :remove_access_privilege
  attr_accessible :center_ids, :centers
  validate :has_centers? , :unless => :full_time?

  has_and_belongs_to_many :zones, :join_table => "zones_teachers", :before_add => :before_add_zone, :after_add => :after_add_zone, :before_remove  => :before_remove_zone, :after_remove  => :after_remove_zone
  has_and_belongs_to_many :secondary_zones, class_name: "Zone", :join_table => "secondary_zones_teachers", :before_add => :before_add_zone, :after_add => :after_add_zone, :before_remove  => :before_remove_zone, :after_remove  => :after_remove_zone
  attr_accessible :zone_ids, :zones, :secondary_zones, :secondary_zone_ids
  validate :primary_secondary_zone?
  #validate :has_zone?


  # Commented for now as there is no definition for this
 # validate :is_unfit?

  has_and_belongs_to_many :program_types
  attr_accessible :program_type_ids, :program_types
  validate :has_program_types?

  has_and_belongs_to_many :co_teacher_program_types, class_name: "ProgramType", join_table: "program_types_co_teachers"
  attr_accessible :co_teacher_program_type_ids, :co_teacher_program_types

  has_and_belongs_to_many :organizing_teacher_program_types, class_name: "ProgramType", join_table: "program_types_organizing_teachers"
  attr_accessible :organizing_teacher_program_type_ids, :organizing_teacher_program_types

  has_and_belongs_to_many :hall_teacher_program_types, class_name: "ProgramType", join_table: "program_types_hall_teachers"
  attr_accessible :hall_teacher_program_type_ids, :hall_teacher_program_types

  has_and_belongs_to_many :initiation_teacher_program_types, class_name: "ProgramType", join_table: "program_types_initiation_teachers"
  attr_accessible :initiation_teacher_program_type_ids, :initiation_teacher_program_types

  PROGRAM_TYPES = {
      ::TeacherSchedule::ROLE_MAIN_TEACHER => "program_types",
      ::TeacherSchedule::ROLE_CO_TEACHER => "co_teacher_program_types",
      ::TeacherSchedule::ROLE_ORGANIZING_TEACHER => "organizing_teacher_program_types",
      ::TeacherSchedule::ROLE_HALL_TEACHER => "hall_teacher_program_types",
      ::TeacherSchedule::ROLE_INITIATION_TEACHER => "initiation_teacher_program_types"
  }

  PROGRAM_TYPES_TABLES = {
      ::TeacherSchedule::ROLE_MAIN_TEACHER => "program_types_teachers",
      ::TeacherSchedule::ROLE_CO_TEACHER => "program_types_co_teachers",
      ::TeacherSchedule::ROLE_ORGANIZING_TEACHER => "program_types_organizing_teachers",
      ::TeacherSchedule::ROLE_HALL_TEACHER => "program_types_hall_teachers",
      ::TeacherSchedule::ROLE_INITIATION_TEACHER => "program_types_initiation_teachers",
  }

  belongs_to :user
  attr_accessible :user_id, :user
  validates :user_id, :presence => true
  validates_uniqueness_of :user_id, :scope => :deleted_at


  attr_accessor :comment_category
  attr_accessible :comment_category

  attr_accessible :t_no
  validates :t_no, :presence => true, :length => { :in => 1..9}
#  validates :email, :uniqueness => true, :format => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}

  has_many :teacher_schedules, :dependent => :destroy
  has_many :timings, through: :teacher_schedules
  attr_accessible :teacher_schedules, :teacher_schedule_ids

  attr_accessible :comments, :additional_comments, :capabilities

  after_initialize :init

  attr_accessible :state
  validates :state, :presence => true

  attr_accessible :full_time

  #before_save :load_last_state
  #before_save :before_save_set_state
  # NOTE - please add any additional post-save cleanup to the function below.
  # Do not add any new function. This is because we are manipulating dirty flag
  # in the function below, due to some HABTM HACK, and *_change when called in another
  # chained after_save function will fail
  after_save :after_save_cleanup

  STATE_UNATTACHED  = 'Not Attached'
  STATE_ATTACHED    = 'Attached'

  FINAL_STATES = []

  # The attach functionality need to be exercised through the admin interface only,
  # since zone(s) and center(s) need to be linked again
  # It is still defined here only for logging and notification purposes
  EVENT_ATTACH      = 'Attach '
  EVENT_UNATTACH    = 'Unattach'

  PROCESSABLE_EVENTS = []



  def init
    self.state  ||= STATE_UNATTACHED
  end

  #state_machine :state, :initial => STATE_UNATTACHED do
  #end

  #def load_last_state
  #  self.last_state = Teacher.find(self.id).state
  #rescue ActiveRecord::RecordNotFound
  #  self.last_state = STATE_UNATTACHED
  #end

  def all_zones
    self.zones + self.secondary_zones
  end

  def before_add_zone(zone)
    self.state = STATE_ATTACHED if self.all_zones.blank?
    return true
  end

  def after_add_zone(zone)
    # for full-time, add centers corresponding to zone
    if self.full_time?
      # remove once to avoid duplicates
      self.centers -= zone.centers
      # add the centers
      self.centers += zone.centers
    end
  end

  def before_remove_zone(zone)
    if self.in_schedule?(zone)
      self.errors.add(:base, " #{zone.name} cannot be un-attached. Teacher is linked to a program. Please remove teacher from linked program(s) and try again.")
      return false
    end

    # set the new value of states
    self.state = STATE_UNATTACHED if self.all_zones == [zone]
    return true
  end

  def after_remove_zone(zone)
    # for full-time, remove centers corresponding to zone
    self.centers -= zone.centers if self.full_time?
  end

  def after_save_cleanup
    changes = self.changes
    return if changes.blank?

    # STEP-1 : First identify all the changed values that we are interested in
    current_state = self.state
    state_changed = changes.has_key?(:state)
    last_state = self.changes[:state][0] if state_changed

    full_time_changed = changes.has_key?(:full_time)

    # STEP-2 : HACK to handle HABTM in after_save
    # HACK - all this making the program_types and centers dirty and reloading the object
    # due to open rails bug attr_writer :hen trying to save a model with habtm in after_create
    # https://rails.lighthouseapp.com/projects/8994/tickets/4553-habtm-association-failure-to-save-in-join-table-with-after_create-callback
    if state_changed or (full_time_changed and self.full_time?)
      temp_program_types = {}
      ::Teacher::PROGRAM_TYPES.each{ |role, value|
        temp_program_types[role] = eval("self." + value)
      }
      #program_types = self.program_types
      centers = self.centers
      zones = self.zones
      secondary_zones = self.secondary_zones
      self.reload
      ::Teacher::PROGRAM_TYPES.each{ |role, value|
        eval("self.#{value} = temp_program_types[\"#{role}\"]")
      }
      #self.program_types = program_types
      self.centers = centers
      self.zones = zones
      #self.secondary_zones = secondary_zones
    end

    # STEP-3 : Now make the changes ... for teacher changed from part-time to full-time
    if (full_time_changed and self.full_time?)
      # Change # 1 - delete published schedules
      self.delete_published_schedules if self.has_published_schedules?

    # Change # 2 - update centers for attached zones
      self.centers = []
      all_zones = self.zones + self.secondary_zones
      all_zones.each { |zone|
        self.centers += zone.centers
      }
      self.save
    end

    # STEP - 4 - send out notifications if either un-attached, or attached
    if state_changed
      if current_state == STATE_ATTACHED
        event = EVENT_ATTACH
      elsif current_state == STATE_UNATTACHED and last_state == STATE_ATTACHED
        event = EVENT_UNATTACH
      else
        event = nil
      end

      unless event.nil?
        # TODO - see how we can get the current_user here?
        self.store_last_update!(nil, last_state, current_state, nil)
        self.save
        self.notify(last_state, current_state, event, self.centers, self)
      end
    end
  end



  def has_published_schedules?(zones = [])
    if zones.blank?
      self.teacher_schedules.where('state IN (?) AND start_date >= ?', ::TeacherSchedule::STATE_PUBLISHED, Time.zone.now.to_date).count > 0
    else
=begin
      zones_centers_ids = []
      zones.each { |zone|
        zones_centers_ids += zone.center_ids
      }
      # if *any* of the center(s) specified in the teacher schedule, falls in the specified zone
      teacher_schedules = self.teacher_schedules.joins("JOIN centers_teacher_schedules ON teacher_schedules.id = centers_teacher_schedules.teacher_schedule_id").where('teacher_schedules.state IN (?) AND teacher_schedules.start_date >= ? AND centers_teacher_schedules.center_id IN (?)', ::TeacherSchedule::STATE_PUBLISHED, Time.zone.now.to_date, zones_centers_ids)
      # only if all the centers for the schedule fall in the zone
      count = 0
      teacher_schedules.each { |ts|
        count += 1 if (ts.center_ids - zones_centers_ids).blank?
      }
      return count
=end
    end
  end

  def delete_published_schedules(zones = [])
    if zones.blank?
      self.teacher_schedules.where('state IN (?) AND start_date >= ?', ::TeacherSchedule::STATE_PUBLISHED, Time.zone.now.to_date).delete_all
    else
=begin
      zones_centers_ids = []
      zones.each { |zone|
        zones_centers_ids += zone.center_ids
      }
      # if *any* of the center(s) specified in the teacher schedule, falls in the specified zone

app/helpers/program_teacher_schedules_helper.rb
module ProgramTeacherSchedulesHelper

  def program_teacher_schedule_state_tag(pts)
    proc do
      if pts.state == ::ProgramTeacherSchedule::STATE_BLOCKED
        '<span class="label label-danger">Blocked</span>'
      elsif pts.state == ::ProgramTeacherSchedule::STATE_BLOCK_REQUESTED
        '<span class="label label-warning">Block Requested</span>'
      elsif pts.state == ::ProgramTeacherSchedule::STATE_ASSIGNED
        '<span class="label label-success">Assigned</span>'
      elsif pts.state == ::ProgramTeacherSchedule::STATE_RELEASE_REQUESTED
        '<span class="label label-warning">Release Requested</span>'
      elsif pts.state == ::ProgramTeacherSchedule::STATE_IN_CLASS
        '<span class="label label-info">In Class</span>'
      elsif pts.state == ::ProgramTeacherSchedule::STATE_COMPLETED_CLASS
        '<span class="label label-default">Completed Class</span>'
      else
        '<span class="label label-default">Unknown</span>'
      end
    end.call().html_safe
  end
end

app/views/program_teacher_schedules/_form.html.erb
<%= form_for(@program_teacher_schedule, :html => { :class => 'form' }) do |f| %>
  <%= resource_error_messages!(@program_teacher_schedule) %>
  <% submit_disabled = false %>

  <% if @program_teacher_schedule.program_id and not @program_teacher_schedule.program_id == 0 %>
      <div class='form-group'>
        <label for='program_id'>Program ID</label>
        <% program = Program.find(@program_teacher_schedule.program_id) %>
        <%= f.text_field :program_display_name, :value=> "#{program.pid if program} - #{program.name if program}", :readonly => true, :id => 'program_id_field', :class => 'form-control' %>
        <%= f.hidden_field :program_id, :value=> @program_teacher_schedule.program_id, :id => :program_id_hidden, :class => 'form-control' %>
      </div>
      <div class='form-group'>
        <label for='teacher_role'>Role</label>
        <%= f.select :teacher_role, options_for_select(@teacher_roles, [@selected_teacher_role]), {}, :id => 'teacher_role_select_1', :class => 'form-control' %>
      </div>
      <div class='form-group'>
        <label for='teacher_id'>Teacher</label>
        <% blockable_teachers =  @blockable_teachers.map {|e| e[:teacher]} %>
        <%= f.hidden_field :blockable_timing_ids, :value=> @blockable_timing_ids, :id => :blockable_timing_ids_hidden, :class => 'form-control' %>
        <% unless blockable_teachers.blank? %>
            <%= f.select :teacher_id, options_for_select(blockable_teachers.map {|t| [t.user.fullname, t.id] }), {}, :id => 'teachers_select', :class => 'form-control' %>
        <% else %>
            <% submit_disabled = true %>
            <%= f.select :teacher_id, options_for_select(['None Available']), {:disabled => true}, :id => 'teachers_select', :class => 'form-control' %>
        <% end %>
      </div>
      <div id="timings" class="form-group">
        <label for='timings'>Timing(s)</label><small> for which Teacher is Available. This may be different from Program Timing(s).</small>
        <% timings =  @selected_timings %>
        <% unless timings.blank?  %>
            <%= f.select :timing_ids, options_for_select(timings.map {|e| [e.name, e.id]}), {}, :multiple => true, :id => 'timing_ids_select', :class => 'form-control' %>
        <% else %>
            <%= f.select :timing_ids, options_for_select(['None Available']), {:disabled => true}, :multiple => true, :id => 'timing_ids_select', :class => 'form-control' %>
        <% end %>
        <small><i>NOTE: </i>Program Timing(s) are <%= @program_teacher_schedule.program.display_timings %></small>
      </div>
      <div class='form-group'>
        <label for='additional_comments'>Note for Scheduler</label>
        <%= f.text_field :additional_comments, :value=> @additional_comments, :readonly => true, :id => 'additional_comments_field', :class => 'form-control' %>
      </div>
        <div class='form-group'>
          <label for='capabilities'>Teacher Capabilities</label>
          <%= f.text_field :capabilities, :value=> @capabilities, :readonly => true, :id => 'capabilities_field', :class => 'form-control' %>
        </div>
    <% elsif @program_teacher_schedule.teacher %>
        <%#= hidden_field_tag 'teacher_id', @program_teacher_schedule.teacher_id %>
        <div class='form-group'>
          <label for='teacher_id'>Teacher ID</label>
          <%= f.text_field :teacher_id, :value=> @program_teacher_schedule.teacher_id, :readonly => true, :id => 'teacher_id_field', :class => 'form-control' %>
        </div>
          <div class='form-group'>
            <label for='teacher_role'>Role</label>
            <%= f.select :teacher_role, options_for_select(@teacher_roles, [@selected_teacher_role]), {}, :id => 'teacher_role_select_2', :class => 'form-control' %>
          </div>
          <div class='form-group'>
          <label for='program_id'>Program</label>
          <% blockable_programs =  @blockable_programs.map {|e| e[:program]} %>
          <%= f.hidden_field :blockable_timing_ids, :value=> @blockable_timing_ids, :id => :blockable_timing_ids_hidden, :class => 'form-control' %>
          <% if blockable_programs.count > 0 %>
              <%= f.select :program_id, options_for_select(blockable_programs.map {|e| [e.friendly_name, e.id] }), {}, :id => 'programs_select', :class => 'form-control' %>
          <% else %>
              <% submit_disabled = true %>
              <%= f.select :program_id, options_for_select(['None Available']), {:disabled => true}, :id => 'programs_select', :class => 'form-control' %>
          <% end %>
        </div>
        <div id="timings" class="form-group">
          <label for='timings'>Timing(s)</label><small> for which Teacher is Available. This may be different from Program Timing(s).</small>
          <% timings =  @selected_timings %>
          <% program_timing_str = @selected_program.blank? ? "" : @selected_program.display_timings %>
          <% unless timings.blank?  %>
              <%= f.select :timing_ids, options_for_select(timings.map {|e| [e.name, e.id]}), {}, :multiple => true, :id => 'timing_ids_select', :class => 'form-control' %>
          <% else %>
              <%= f.select :timing_ids, options_for_select(['None Available']), {:disabled => true}, :multiple => true, :id => 'timing_ids_select', :class => 'form-control' %>
          <% end %>
          <% unless program_timing_str.blank? %>
            <small><i>NOTE: </i>Program Timing(s) are <%= f.label program_timing_str, :id => 'program_timings_label' %></small>
          <% end %>
        </div>

    <% end %>

  <%= f.submit 'Associate Teacher with Program', :disabled => submit_disabled, :id => 'submit_button', :class => 'btn btn-lg btn-primary' %>
<% end %>


<script type='text/javascript'>
$('.dateSelect').datepicker({dateFormat: 'd MM yy (DD)'});
</script>

<script>
    $(document).ready(function() {
        $('#teacher_role_select_1').change(function() {
            $.ajax({
                url: "<%= update_program_teacher_schedule_blockable_teachers_path %>",
                data: {
                    teacher_role_val : $('#teacher_role_select_1').val(),
                    program_id : $('#program_id_hidden').val()
                },
                dataType: "script"
            });
        });
        $('#teacher_role_select_2').change(function() {
            $.ajax({
                url: "<%= update_program_teacher_schedule_blockable_programs_path %>",
                data: {
                    teacher_role_val : $('#teacher_role_select_2').val(),
                    teacher_id : $('#teacher_id_field').val()
                },
                dataType: "script"
            });
        });
        $('#teachers_select').change(function() {
            $.ajax({
                url: "<%= update_program_teacher_schedule_additional_comments_path %>",
                data: {
                    teacher_id : $('#teachers_select').val(),
                    blockable_timing_ids : $('#blockable_timing_ids_hidden').val()
                },
                dataType: "script"
            });
        });
        $('#programs_select').change(function() {
            $.ajax({
                url: "<%= update_program_teacher_schedule_program_timings_path %>",
                data: {
                    program_id : $('#programs_select').val(),
                    blockable_timing_ids : $('#blockable_timing_ids_hidden').val()
                },
                dataType: "script"
            });
        });
        <% if @hide_timings %>
            $("#timings").hide();
        <% else %>
            $("#timings").show();
        <% end %>
    });
</script>

app/views/program_teacher_schedules/_state_bar.html.erb
<h2>
  <% @program_teacher_schedule = pts %>
  <small><%= program_teacher_schedule_state_tag(@program_teacher_schedule) %></small>
  Program-Teacher Schedule
  <small><%= @program_teacher_schedule.program.name %> | <%= @program_teacher_schedule.teacher.user.fullname %> </small>

  <% unless ::ProgramTeacherSchedule::FINAL_STATES.include?(@program_teacher_schedule.state) %>
      <div class='btn-group'>
        <button type="button" class="btn btn-danger">Update State</button>
        <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">
          <span class="caret"></span>
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <% events = (@program_teacher_schedule.state_events - ::Program::NOTIFICATIONS) %>
          <% if events.count > 0 %>
              <% events.each do |ev| %>
                  <li> <%= link_to ev, edit_program_teacher_schedule_path(:id => id, :trigger => ev) %> </li>
              <% end %>
          <% else %>
              <li class="disabled"><a href="#">No Action Available</a></li>
          <% end %>
         </ul>
      </div>
  <% end %>

<span class='pull-right'>
    <%= link_to "Back to Schedules", teacher_teacher_schedules_path(@program_teacher_schedule.teacher), :class => 'btn btn-primary' %>
</span>
</h2>

app/views/program_teacher_schedules/_state_update_comment.html.erb
<div class='form-group'>
  <% if ::ProgramTeacherSchedule::EVENTS_WITH_COMMENTS.include?(@trigger) %>
      <% unless @program_teacher_schedule.comment_category.empty? %>
          <label for='comment_category'>Comments</label> <small>(required)</small>
          <%= select_tag 'comment_category', options_for_select(@program_teacher_schedule.comment_category), :class => 'form-control' %>
          <br>
          <label>Details</label>
          <textarea name='comments' class='form-control'></textarea>
      <% else %>
          <label>Comments</label> <small>(required)</small>
          <textarea name='comments' class='form-control'></textarea>
      <% end %>
  <% elsif ::ProgramTeacherSchedule::EVENTS_WITH_FEEDBACK.include?(@trigger) %>
      <label>Feedback</label> <small>(required)</small>
      <textarea name='feedback' class='form-control'></textarea>
  <% else %>
      <label>Comments</label> <small>(optional)</small>
      <textarea name='comments' class='form-control'></textarea>
  <% end %>
</div>

app/views/program_teacher_schedules/_state_update_confirmation_msg.html.erb
<% if ::ProgramTeacherSchedule::EVENTS_WITH_COMMENTS.include?(@trigger) %>
    <div class='alert alert-warning'>
<% else %>
    <div class='alert alert-info'>
<% end %>
<h3>Confirmation: </h3>
<p>
     <% if @trigger == ::ProgramTeacherSchedule::EVENT_RELEASE %>
          <strong>WARNING: </strong> This will remove the teacher from the program. Are you sure you want to proceed?
     <% elsif @trigger == ::ProgramTeacherSchedule::EVENT_CANCEL %>
      <strong>WARNING: </strong> This will remove the teacher from the program. Are you sure you want to proceed?
      <% elsif @trigger == ::ProgramTeacherSchedule::EVENT_REQUEST_RELEASE %>
          Are you sure you want to change state of teacher to<strong> Request Release </strong> for this Program?
      <% elsif @trigger == ::ProgramTeacherSchedule::EVENT_BLOCK %>
          Are you sure you want to change state of teacher to<strong> Block </strong> for this Program?
      <% end %>
</p>
</div>

app/views/program_teacher_schedules/show.html.erb
<% if @program_teacher_schedule.can_update? %>
    <div class='row'>
      <div class='col-md-12'>
        <%= render :partial => 'program_teacher_schedules/state_bar', locals: {pts: @program_teacher_schedule, id: @program_teacher_schedule.teacher_schedule.id } %>
      </div>
    </div>
    <% teacher_schedule = @program_teacher_schedule.teacher_schedule %>
    <div class='row'>
      <div class='col-md-12'>
        <h3>Last Update <small><%= teacher_schedule.last_update %></small></h3>
        <div class = 'row'>
          <div class='col-md-12'>
            <table class='table table-bordered'>
              <tr>
                <td width='20%'><strong> Updated By </strong></td>
                <td>
                    <%= teacher_schedule.last_updated_by_user.fullname rescue ' ' %>
                </td>
              </tr>
              <tr>
                <td><strong> Updated At </strong></td>
                <td><%= teacher_schedule.last_updated_at.strftime('%d %B %Y (%I:%M%P)') rescue ' ' %></td>
              </tr>
              <tr>
                <td><strong> Comments </strong></td>
                <td><%= teacher_schedule.comments %></td>
              </tr>
              <% if current_user.is? :zao, :center_id => teacher_schedule.program.center_id %>
                  <% unless teacher_schedule.feedback.nil? %>
                      <tr>
                        <td><strong> Feedback </strong></td>
                        <td><%= teacher_schedule.feedback %></td>
                      </tr>
                  <% end %>
              <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class='row'>
      <div class='col-md-12'>
        <h3>Details</h3>
        <div class='row'>
          <div class='col-md-12'>
            <table class='table table-bordered'>
              <tr>
                <td width='20%'><strong>ID #</strong></td>
                <td><%= teacher_schedule.id %></td>
              </tr>
              <tr>
                <td><strong>Program</strong></td>
                <td><%= link_to "#{teacher_schedule.program.name}", program_path(teacher_schedule.program) %></td>
              </tr>
              <tr>
                <td><strong>Teacher</strong></td>
                <td><%= link_to "#{teacher_schedule.teacher.user.fullname}", teacher_path(teacher_schedule.teacher) %></td>
              </tr>
              <tr>
                <td><strong>Role</strong></td>
                <td><%= teacher_schedule.role %></td>
              </tr>
              <tr>
                <td><strong>Center</strong></td>
                <td><%= teacher_schedule.program.locality_name %></td>
              </tr>
              <tr>
                <td><strong>Booking Start Date</strong></td>
                <td><%= teacher_schedule.program.start_date.strftime('%d %B %Y (%A)') %></td>
              </tr>
              <tr>
                <td><strong>Booking End Date</strong></td>
                <td><%= teacher_schedule.program.end_date.strftime('%d %B %Y (%A)') %></td>
              </tr>
              <tr>
                <td><strong>Timing (s)</strong></td>
                <td><%= teacher_schedule.display_timings(teacher_schedule.role) %></td>
              </tr>
              <tr>
                <td><strong>Blocked By</strong></td>
                <td><%= teacher_schedule.blocked_by_user.fullname rescue ' '%></td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
<% end %>